name: Trigger Cloudflare Worker
on:
  schedule:
     - cron: "00 01 * * *" # 01:00 UTC mỗi ngày
  workflow_dispatch: # Cho phép kích hoạt thủ công
jobs:
  trigger-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Worker
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          TRIGGER_SECRET: ${{ secrets.TRIGGER_SECRET }}
        run: |
          curl -X POST $WORKER_URL/trigger \
            -H "Content-Type: application/json" \
            -H "X-Trigger-Secret: $TRIGGER_SECRET" \
            -d '{}'
